<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8ec4btZ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8ec4btZ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8ec4btZ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8ec4btZ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container8ec4btZ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '8ec4btZ',
    'container.build_id' => 'd91ea1b3',
    'container.build_time' => 1574257896,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8ec4btZ');
